apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-platform-operators
  namespace: openshift-gitops
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-gatekeeper-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: critical
          subscription:
            name: gatekeeper-operator-product
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-pipelines-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: critical
          subscription:
            name: openshift-pipelines-operator-rh
            channel: latest
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-gitops-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: critical
          subscription:
            name: openshift-gitops-operator
            channel: latest
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            config:
              env:
                - name: NAMESPACE_SCOPED_ARGO_ROLLOUTS
                  value: 'false'
                - name: CLUSTER_SCOPED_ARGO_ROLLOUTS_NAMESPACES
                  value: demo-rollouts
          upgradeApproval: Automatic
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-devspaces-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: critical
          subscription:
            name: devspaces
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
          upgradeApproval: Automatic
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-gitops-operator
  namespace: openshift-gitops
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-gitops-operator
        spec:
          complianceType: musthave
          remediationAction: enforce
          severity: critical
          subscription:
            name: openshift-gitops-operator
            channel: latest
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            config:
              env:
                - name: NAMESPACE_SCOPED_ARGO_ROLLOUTS
                  value: 'false'
                - name: CLUSTER_SCOPED_ARGO_ROLLOUTS_NAMESPACES
                  value: demo-rollouts
          upgradeApproval: Automatic
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: require-gatekeeper-labels-on-ns
spec:
  remediationAction: inform 
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: templates.gatekeeper.sh/v1beta1
        kind: ConstraintTemplate
        metadata:
          name: k8srequiredlabels
          annotations:
            policy.open-cluster-management.io/severity: low 
        spec:
          crd:
            spec:
              names:
                kind: K8sRequiredLabels
              validation:
                openAPIV3Schema:
                  properties:
                    labels:
                      type: array
                      items: string
          targets:
            - target: admission.k8s.gatekeeper.sh
              rego: |
                package k8srequiredlabels
                violation[{"msg": msg, "details": {"missing_labels": missing}}] {
                  provided := {label | input.review.object.metadata.labels[label]}
                  required := {label | label := input.parameters.labels[_]}
                  missing := required - provided
                  count(missing) > 0
                  msg := sprintf("you must provide labels: %v", [missing])
                }
    - objectDefinition:
        apiVersion: constraints.gatekeeper.sh/v1beta1
        kind: K8sRequiredLabels
        metadata:
          name: ns-must-have-gk
          annotations:
            policy.open-cluster-management.io/severity: low 
        spec:
          enforcementAction: dryrun
          match:
            kinds:
              - apiGroups: [""]
                kinds: ["Namespace"]
          parameters:
            labels: ["gatekeeper"]